networks:
  rentcarx-dev:
    name: rentcarx-dev-network
    driver: bridge

volumes:
  sqlserver_data:

services:
  rentcarx:
    image: rentcarx:latest 
    networks:
      - rentcarx-dev

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    networks: 
      - rentcarx-dev

  rentcarx-hangfire:
    build: ./RentCarX.HangfireWorker
    depends_on:
      - sqlserver


  